### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by flydev-fr** [flydev-fr/MarkupGoogleRecaptcha#3]
- full update
- FormBuilder examples

**Comment by jimmytricks** [comment]
Hey @flydev-fr ,

Great work with the module, though I'm having an issue is getting it working with FormBuilder. I can see the recaptcha, though the form will submit whether it is ticked or not. I'm using embed method D but not sure how to use $captcha->verifyResponse() === true, before the form is submitted. 

Any help would be great, cheers :)

**Comment by flydev-fr** [comment]
Thanks @jimmytricks  

Have you tried my example posted in the forum thread ?  

https://processwire.com/talk/topic/13738-markup-google-recaptcha/page/2/?tab=comments#comment-179574

**Comment by jimmytricks** [comment]
Hey @flydev-fr , yup I did give that a read but I was struggling to figure out how to use a hook to check recaptcha result before submitting. I found a resolution in the end using:

`$forms->addHookBefore('FormBuilderProcessor::processInputDone', function ($e) use ($captcha) {`
`$form = $e->arguments(0); // retrieve argument by number (zero based)`
	`if ($captcha->verifyResponse() === true) {`
	`} else { `
        `$form->error('Recaptcha is missing. Please tick I\'m not a robot and try again');`
	`}`
`});`

Some useful info here about FormBuilder hooks too: https://processwire.com/blog/posts/formbuilder-v34/

Hope that helps, cheers again for the module :)

**Comment by flydev-fr** [comment]
Ok I misread your previous post. 

Anyway good catch about the hook - thanks for code chunk.
